name: Docker Scout

on: [push]

jobs:
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    # - name: Docker Scout Scan
      # run: |
        # curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        # sh install-scout.sh
        # echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
        # docker scout quickview
        # docker scout cves

    # https://github.com/marketplace/actions/docker-scout
    - name: Docker Scout Scan
      uses: docker/scout-action@v1.17.1
      with:
        dockerhub-user: ${{ secrets.REPO_USER }}
        dockerhub-password: ${{ secrets.REPO_PWD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif
        # exit-code: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif
