name: Secure CI/CD Pipeline

on:
  push:
    branches: [master] 

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write  # Required for uploading SARIF results to GitHub Security tab

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          upload: always
